# 测试输出格式的简单配置
device: 'cuda'

experiment_info:
  author: Test
  version: '1.0'

datasets:
  NASA_IMS:
    train_data: ./data/NASA_IMS/train_X.npy
    train_label: ./data/NASA_IMS/train_y.npy
    test_data: ./data/NASA_IMS/test_X.npy
    test_label: ./data/NASA_IMS/test_y.npy
    preprocessing:
      normalize: false

models:
  LSTM:
    hidden_dim: 64
    num_layers: 2
    dropout: 0.2

training_templates:
  debug:
    type: supervised
    batch_size: 64
    epochs: 2
    lr: 0.001
    patience: 1
    optimizer: 'adam'
    print_interval: 1
    data_fraction: 0.01

experiments:
  - name: "Test_Output"
    model: "LSTM"
    dataset: "NASA_IMS"
    training: "debug"
    evaluation: "default"

evaluation_templates:
  default:
    metrics:
      f1:

output:
  generate_plots: false
  results_dir: ./results
  save_models: false
  save_results: false
  comparison_report: true