# 超参数调优实验配置
# ====================
# 
# 实验名称: LSTM AutoEncoder超参数优化
# 目标: 通过网格搜索找到最佳超参数组合
# 作者: Fault Diagnosis Benchmark Team
# 日期: 2025-01-11

experiment:
  name: "lstm_ae_hyperparameter_tuning"
  description: "LSTM AutoEncoder超参数网格搜索"
  version: "1.0"
  author: "Benchmark Team"
  tags:
    - "hyperparameter_tuning"
    - "lstm_autoencoder"
    - "optimization"

# 数据配置
data:
  dataset: "swat"
  train_file: "../data/raw/swat_train.csv"
  test_file: "../data/raw/swat_test.csv"
  preprocessing:
    normalize: true
    fill_missing: true

# 超参数搜索配置
hyperparameter_search:
  method: "grid_search"  # grid_search, random_search, bayesian
  
  # 搜索空间定义
  param_grid:
    hidden_dim: [32, 64, 128]
    num_layers: [1, 2, 3]
    dropout: [0.1, 0.2, 0.3]
    lr: [0.0001, 0.001, 0.01]
    batch_size: [16, 32, 64]
  
  # 搜索参数
  n_trials: 50  # 对于random_search和bayesian
  cv_folds: 3   # 交叉验证折数
  
  # 优化目标
  optimization_metric: "f1"  # f1, precision, recall, auc
  optimization_direction: "maximize"  # maximize, minimize
  
  # 早停配置
  early_stopping:
    enabled: true
    patience: 5
    min_improvement: 0.001

# 基础模型配置（固定参数）
model_base_config:
  epochs: 30
  patience: 10
  random_state: 42
  device: "auto"
  verbose: false

# 评估配置
evaluation:
  metrics:
    - "f1"
    - "precision"
    - "recall"
    - "auc"
  
  auto_threshold: true

# 输出配置
output:
  save_results: true
  results_dir: "../results/hyperparameter_tuning"
  
  # 保存最佳模型
  save_best_model: true
  
  # 生成调优报告
  generate_tuning_report: true
  
  # 保存所有试验结果
  save_all_trials: true
  
  # 可视化
  generate_plots: true
  plot_types:
    - "parameter_importance"
    - "optimization_history"
    - "parameter_correlations"
